db-uri = "postgres://postgres:PAROLINGIZ@localhost:5432/BAZA_NOMI"
db-schemas = "public"
db-anon-role = "postgres" # Ishlab chiqish uchun (prod uchun alohida read-only rol yaratgan ma'qul)
server-port = 3000

